### ISSUE TITLE
Issue with slideshow module breaking publishing

### ISSUE THREAD

**Issue by slip13420** [silexlabs/Silex#1131]
Hey guys, weird issue.  I've been trying to set things up as a standalone instance working in single page mode.  All of that is working fine, can add images from SFTP, save the site, publish the site, no problem.  Problem occurs when I add the slideshow module.  The pictures seem to load fine in the editor, however the "choose file" section never shows the preview and just continues to say "choose file".
![image](https://user-images.githubusercontent.com/52355525/124320337-8c148400-db30-11eb-931e-cfcbed4f6531.png)
This saves fine and has no issue in the editor.  Then when I publish the file I get an error regarding ssh... 
![image](https://user-images.githubusercontent.com/52355525/124320395-b1a18d80-db30-11eb-8a78-d2ee9f404014.png)
Error I get in the logs is...
`An error occured in write operations { Error: (SSH) Channel open failure: open failed
    at SSH2Stream.onFailure (/home/ubuntu/silex_test/app/node_modules/ssh2/lib/client.js:1205:13)
    at Object.onceWrapper (events.js:286:20)
    at SSH2Stream.emit (events.js:198:13)
    at parsePacket (/home/ubuntu/silex_test/app/node_modules/ssh2-streams/lib/ssh.js:3455:10)
    at SSH2Stream._transform (/home/ubuntu/silex_test/app/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/home/ubuntu/silex_test/app/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at SSH2Stream.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:710:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10) reason: 'CONNECT_FAILED', lang: '' }
Warning: possible error in PublishJob 006fd9ce-02ad-48c4-b8b9-59dabe819849 (true)
`
This only happens when I use the slideshow module.  Any help appreciated!

**Comment by lexoyo** [comment]
Oh this is really strange
Could you try to publish with another service and see if it works maybe? File system may be the easiest one

**Comment by slip13420** [comment]
Roger that, will try.

**Comment by slip13420** [comment]
Ok, so I switched it to use the fs connector and set my fs_root to a user folder in /home/.  Running silex as root currently for testing purposes.  I am able to open the page with the correct path and service settings.  The page opens and is editable.  However if I try to add images from that folder or browse it at all I get an out of sandbox error, 
![image](https://user-images.githubusercontent.com/52355525/124962784-e51e6500-dfd3-11eb-8d5b-47b4ec4fc7ef.png)
.  I also get the same error when doing a save website.  Error below.
Warning local file system is writable, use FS_ROOT as root ( /home/sftpuser/ )
Publication error, could not get website files: Error: No session provided
    at Unifile.callMethod (/home/ubuntu/silex_test/app/node_modules/unifile/lib/index.js:338:22)
    at Unifile.readFile (/home/ubuntu/silex_test/app/node_modules/unifile/lib/index.js:261:15)
    at getSite (/home/ubuntu/silex_test/app/node_modules/silex-website-builder/dist/server/server/router/WebsiteRouter.js:61:42)
    at /home/ubuntu/silex_test/app/node_modules/silex-website-builder/dist/server/server/router/WebsiteRouter.js:87:48
    at Layer.handle [as handle_request] (/home/ubuntu/silex_test/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/silex_test/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/silex_test/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/silex_test/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:281:22
    at param (/home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:354:14)
    at param (/home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:365:14)
    at param (/home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:410:3)
    at next (/home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:174:3)
    at router (/home/ubuntu/silex_test/app/node_modules/express/lib/router/index.js:47:12)
I've tried running it as non root and have the same issue.  I also tried setting the html and json file to 777, no dice.  Any help appreciated.

**Comment by slip13420** [comment]
Update to this, looking through CloudExplorerRouter.js I see that the sandbox being passed is just fsRoot and I have the environment variable set... FS_ROOT=/home/sftpuser.  Not sure where to go from here lol.  Any help appreciated.  Thanks in advance!

**Comment by lexoyo** [comment]
Hello
Your environment variable is ok (FS_ROOT) [as you can see here](https://github.com/silexlabs/Silex/blob/develop/src/ts/server/ServerConfig.ts#L92), Silex builds CE options with env vars
I looked at the code and I dont see why. Where do you save the website/what path? Is it inside the root path?

**Comment by lexoyo** [comment]
Also I did not ask: what browser do you use?

**Comment by slip13420** [comment]
So folder I'm saving is is the fs_root, path variable in the url is /scott_test.html which works, opens the file fine as it's relative to FS_ROOT correct?  Also, browser is chrome.  I can try in Firefox in a bit.

**Comment by slip13420** [comment]
Same issue in firefox...
![Screenshot_20210709_100339](https://user-images.githubusercontent.com/52355525/125113120-14e56f80-e09d-11eb-929e-f8fdfd2cd3b7.png)

**Comment by slip13420** [comment]
Tried putting the files into a sub directory of the FS_ROOT and changed the path=, same result...
![image](https://user-images.githubusercontent.com/52355525/125127049-d78add00-e0b0-11eb-8e38-e25f69f74909.png)

**Comment by slip13420** [comment]
One other thing I forgot to mention, using pm2 to manage the startup of Silex, not sure if that has any impact.  Started via the command..
`sudo SERVER_URL=http://xxx.xxx.xxx.xxx:6805 ENABLE_FS=true FS_ROOT=/home/sftpuser pm2 start --name silex npm -- start`

**Comment by slip13420** [comment]
Hey guys, update on this.  I have created custom services and custom hosting provider.  Everything works great now, saving, publishing, opening, slideshow, etc.  The only small issue I have is when I have images in the slideshow I still get a no file chosen in the preview window...
![image](https://user-images.githubusercontent.com/52355525/125686141-dd037096-a106-467f-bf9f-aeb8d28696ff.png)
Any ideas?  Thanks in advance guys, love this software!

**Comment by lexoyo** [comment]
Very nice!!!

> The only small issue I have is when I have images in the slideshow I still get a no file chosen in the preview window...

This is a known bug. It probably comes from [the prodotype library](/silexlabs/Prodotype) which is used to generate the components UI

**Comment by lexoyo** [comment]
Feel free to open an issue for this last problem

Also would you share your setup? Maybe as a page in the wiki and/or a github repo?

If I understand correctly you made Silex an admin for just 1 site? It behaves like the back office of a traditional CMS then?

Thank you for sharing

**Comment by slip13420** [comment]
> Feel free to open an issue for this last problem
> 
> Also would you share your setup? Maybe as a page in the wiki and/or a github repo?
> 
> If I understand correctly you made Silex an admin for just 1 site? It behaves like the back office of a traditional CMS then?
> 
> Thank you for sharing

Thanks, I will open a new issue for the new problem.  As for my setup, all I did was copy the various tutorials, [how to add silex to your node.js project](https://github.com/silexlabs/Silex/wiki/How-To-Add-Silex-To-Your-Node.js-Project), [Integrate Silex with your infrastructure](https://github.com/silexlabs/Silex/wiki/Integrate-Silex-with-your-infrastructure), and [single site mode](https://github.com/silexlabs/Silex/wiki/Single-site-mode).  It's setup in /opt/silex with the custom service saving to /opt/website/USERNAME.  After that all I did was configure nginx to serve that directory.  My /etc/nginx/sites-enabled/default looks like this...

`server {
    listen 80;
    server_name 127.0.0.1;

    location / {
        alias /opt/website/USERNAME/Website/;
        client_body_timeout 300s;
        uwsgi_read_timeout 300s;
        index index.html;
    }
}`

I just built a basic template that I copied into /opt/website/USERNAME/editable.html.  So to load silex I just use this URL (replace xxx.xxx with actual IP)....
http://xxx.xxx.xxx.xxx:6805/?path=/editable.html&service=custom-service.

All of this is built into an Odroid XU4 with the hopes that it will eventually be a CMS for a media screen.
