### ISSUE TITLE
Error: Command failed: submodules/closure-library/closure/bin/build/closurebuilder.py: Scanning paths...

### ISSUE THREAD

**Issue by pierreozoux** [silexlabs/Silex#285]
I just got that error.

I followed the instructions on the page. Do you have any hint on how to start to debug?

Thanks for your help!

```
Running "closureBuilder:release" (closureBuilder) task
Executing: python submodules/closure-library/closure/bin/build/closurebuilder.py  -n silex.App --root=submodules/closure-library/ --root=src/js/ -o compiled --output_file=dist/client/js/admin.min.js --compiler_jar=node_modules/superstartup-closure-compiler/build/es6compiler.jar --compiler_flags="--compilation_level=ADVANCED_OPTIMIZATIONS" --compiler_flags="--language_in=ECMASCRIPT6_STRICT" --compiler_flags="--jscomp_error=accessControls" --compiler_flags="--jscomp_error=ambiguousFunctionDecl" --compiler_flags="--jscomp_error=checkRegExp" --compiler_flags="--jscomp_error=checkTypes" --compiler_flags="--jscomp_error=checkVars" --compiler_flags="--jscomp_error=const" --compiler_flags="--jscomp_error=constantProperty" --compiler_flags="--jscomp_error=deprecated" --compiler_flags="--jscomp_error=duplicateMessage" --compiler_flags="--jscomp_error=es5Strict" --compiler_flags="--jscomp_error=externsValidation" --compiler_flags="--jscomp_error=fileoverviewTags" --compiler_flags="--jscomp_error=globalThis" --compiler_flags="--jscomp_error=internetExplorerChecks" --compiler_flags="--jscomp_error=invalidCasts" --compiler_flags="--jscomp_error=missingProperties" --compiler_flags="--jscomp_error=nonStandardJsDocs" --compiler_flags="--jscomp_error=strictModuleDepCheck" --compiler_flags="--jscomp_error=typeInvalidation" --compiler_flags="--jscomp_error=undefinedNames" --compiler_flags="--jscomp_error=undefinedVars" --compiler_flags="--jscomp_error=unknownDefines" --compiler_flags="--jscomp_error=uselessCode" --compiler_flags="--jscomp_error=visibility" --compiler_flags="--language_out=ECMASCRIPT3" --compiler_flags="--warning_level=VERBOSE" --compiler_flags="--define='goog.DEBUG=false'" --compiler_flags="--debug=false" --compiler_flags="--create_source_map=dist/client/js/admin.min.js.map" --compiler_flags="--source_map_format=V3" --compiler_flags="--externs=src/js/externs.js"
>> Error: Command failed: submodules/closure-library/closure/bin/build/closurebuilder.py: Scanning paths...
>> submodules/closure-library/closure/bin/build/closurebuilder.py: 1502 sources scanned.
>> submodules/closure-library/closure/bin/build/closurebuilder.py: Building dependency tree..
>> submodules/closure-library/closure/bin/build/closurebuilder.py: Closure Compiler now natively understands and orders Closure dependencies and
>> is prefererred over using this script for performing JavaScript compilation.
>> 
>> Please migrate your codebase.
>> 
>> See:
>> https://code.google.com/p/closure-compiler/wiki/ManageClosureDependencies
>> 
>> Traceback (most recent call last):
>>   File "submodules/closure-library/closure/bin/build/closurebuilder.py", line 274, in <module>
>>     main()
>>   File "submodules/closure-library/closure/bin/build/closurebuilder.py", line 263, in main
>>     compiler_flags=options.compiler_flags)
>>   File "/home/pierre/f/Silex/submodules/closure-library/closure/bin/build/jscompiler.py", line 125, in Compile
>>     java_version = _ParseJavaVersion(_GetJavaVersionString())
>>   File "/home/pierre/f/Silex/submodules/closure-library/closure/bin/build/jscompiler.py", line 37, in _GetJavaVersionString
>>     return subprocess.check_output(['java', '-version'], stderr=subprocess.STDOUT)
>>   File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
>>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
>>     errread, errwrite)
>>   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
>>     raise child_exception
>> OSError: [Errno 2] No such file or directory
>> FAILED to run command for target: release
Warning: Task "closureBuilder:release" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Silex@0.8.0 postinstall: `grunt deploy`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the Silex@0.8.0 postinstall script.
npm ERR! This is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt deploy
npm ERR! You can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-21-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pierre/f/Silex
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pierre/f/Silex/npm-debug.log
npm ERR! not ok code 0
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by ondrejec** [comment]
Have you install submodule with
git clone --recursive https <https://github.com/silexlabs/Silex.git>://
<https://github.com/silexlabs/Silex.git>github.com
<https://github.com/silexlabs/Silex.git>/
<https://github.com/silexlabs/Silex.git>silexlabs
<https://github.com/silexlabs/Silex.git>/
<https://github.com/silexlabs/Silex.git>Silex.gi
<https://github.com/silexlabs/Silex.git>
Or closure-library with
npm install close-library?

**Comment by pierreozoux** [comment]
Actually, I was missing java :/ sorry :/
