### ISSUE TITLE
Local installation macOS npm install fail

### ISSUE THREAD

**Issue by detectedstealth** [silexlabs/Silex#561]
Following the instructions npm install keeps failing on: Failed at the prodotype@1.0.0 postinstall script 'npm run build:editor'.. And when I clone Prodotype separately and npm install on it there is no issues. 

Am I missing something in the setup instructions?

```
> prodotype@1.0.0 postinstall /Users/brucewade/Development/tools/Silex/node_modules/prodotype
> npm run build:editor


> prodotype@1.0.0 build:editor /Users/brucewade/Development/tools/Silex/node_modules/prodotype
> browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/brucewade/Development/tools/Silex/node_modules/prodotype/node_modules/ejs/ejs.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/brucewade/Development/tools/Silex/node_modules/prodotype/bin/appendejslib:8:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/brucewade/.nvm/versions/node/v6.6.0/bin/node" "/Users/brucewade/.nvm/versions/node/v6.6.0/bin/npm" "run" "build:editor"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! prodotype@1.0.0 build:editor: `browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prodotype@1.0.0 build:editor script 'browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prodotype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prodotype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prodotype
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```
[npm-debug.txt](https://github.com/silexlabs/Silex/files/817550/npm-debug.txt)

**Comment by lexoyo** [comment]
Hi @detectedstealth 
I will investigate this soon
Meanwhile you can use your separate successful clone of Prodotype:
```
$ cd /path/to/Prodotype
$ npm link
$ cd /path/to/Silex
$ npm link prodotype
```
you may need `sudo` for one of the commands
Thank you for the bug report

**Comment by detectedstealth** [comment]
Thanks that work around enables me to get up, running and start diving into the code for now.

**Comment by lexoyo** [comment]
Found it!
The problem was that I was concatenating ejs lib with Prodotype lib, and since ejs was already in Silex, the file `node_modules/prodotype/node_modules/ejs/ejs.min.js` was in fact in `node_modules/ejs/ejs.min.js`
[Fixed by this commit in Prodotype](https://github.com/lexoyo/Prodotype/commit/c360ed3cbee3f92c1b63d02fe13bf35292d5e9ba). You can `npm install` again and it should work.
Thank you for the bug report, let me know what you are doing with Silex?
