### ISSUE TITLE
Failed to build docker image

### ISSUE THREAD

**Issue by fresnizky** [silexlabs/Silex#697]
Hi, I'm trying to build the docker image from source following the instructions in https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex but I'm getting errors during the process.

Here's a log of the error
```
Building template hero-center
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/silex/dist/client/libs/prodotype/components/hero-center.ejs'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /silex/node_modules/prodotype/bin/prodotype:49:8
    at Array.forEach (native)
    at Object.<anonymous> (/silex/node_modules/prodotype/bin/prodotype:30:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

npm info lifecycle Silex@0.8.0~build:prodotype: Failed to exec build:prodotype script
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:prodotype"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build:prodotype: `prodotype src/components dist/client/libs/prodotype/components/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Silex@0.8.0 build:prodotype script 'prodotype src/components dist/client/libs/prodotype/components/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prodotype src/components dist/client/libs/prodotype/components/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /silex/npm-debug.log

npm info lifecycle Silex@0.8.0~build: Failed to exec build script
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build: `npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Silex@0.8.0 build script 'npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /silex/npm-debug.log
The command '/bin/sh -c apt-get update &&  apt-get install -yq python openjdk-7-jre &&  rm -rf /var/lib/apt/lists/* &&  npm install &&  npm run build' returned a non-zero code: 1
```
Is the Dockerfile up to date? Because I saw it still uses Node 6.5.0. How could I solve this?

Thanks,

**Comment by lexoyo** [comment]
oh it looks like the folder for the components is missing, let me check this

**Comment by lexoyo** [comment]
I changed this
https://github.com/silexlabs/Prodotype/commit/a728db38cdf450ebe216dc00ed8130f3092bf0d6

can you try again?

**Comment by lexoyo** [comment]
I tried the docker build. It looks like my fix in the latest prodotype version works
Thx for the bug report

**Comment by fresnizky** [comment]
I tried again from a fresh clone of the repo and still can't build, but I'm getting a different error:
```
> Silex@0.8.0 build:prodotype /silex
> prodotype src/components dist/client/libs/prodotype/components/

Building /silex/src/components to /silex/dist/client/libs/prodotype/components in current dir: /silex
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/silex/dist/client/libs/prodotype/components'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at /silex/node_modules/prodotype/bin/prodotype:33:8
    at Array.forEach (native)
    at Object.<anonymous> (/silex/node_modules/prodotype/bin/prodotype:30:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm info lifecycle Silex@0.8.0~build:prodotype: Failed to exec build:prodotype script
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:prodotype"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build:prodotype: `prodotype src/components dist/client/libs/prodotype/components/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Silex@0.8.0 build:prodotype script 'prodotype src/components dist/client/libs/prodotype/components/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prodotype src/components dist/client/libs/prodotype/components/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /silex/npm-debug.log

npm info lifecycle Silex@0.8.0~build: Failed to exec build script
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build: `npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Silex@0.8.0 build script 'npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /silex/npm-debug.log

```
