### ISSUE TITLE
Silex desktop version

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#797]
I published the 1st release of Silex desktop app, does it look good to you? 
https://github.com/silexlabs/Silex/releases

You can install the app on your computer to work offline and save your work on your local computer.
This is mainly the work of @JbIPS 

Help is needed for the tests, please give us feedback in this issue
* Test silex-2.2.7.dmg on mac
* Test silex-2.2.7-x86_64.AppImage on linux
* Test silex-2.2.7-amd64.deb on linux

What we still need to do
* [x] Windows version(s)
* [x] Mac version(s)
* [x] The `.deb` for x86 linux
* [x] The `.rpm` for x86 linux

Thank you in advance for your help!

**Comment by lexoyo** [comment]
I have tested `silex-2.2.7-x86_64.AppImage`. It starts Silex server but there are several problems

* it does not open the electron app in a widow
* there seem to be no unifile service, not even fs

This is what I did and what I got:

``` 
$ chmod +x Downloads/silex-2.2.7-x86_64.AppImage
$ Downloads/silex-2.2.7-x86_64.AppImage

Silex starts with version [ '2', '2', '7' ]
FTP service: looking for env vars ENABLE_FTP
SFTP service: looking for env vars ENABLE_SFTP
Webdav service: looking for env vars ENABLE_WEBDAV
Github service: looking for env vars GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET
Dropbox service: looking for env vars DROPBOX_CLIENT_ID and DROPBOX_CLIENT_SECRET
Local file system service: looking for env vars SILEX_ELECTRON or SILEX_DEBUG or ENABLE_FS
body-parser deprecated undefined extended: provide extended option ../../tmp/.mount_silex-CNB5VD/resources/app.asar/node_modules/cloud-explorer/lib/router.js:297:53
force SSL NOT active (env var SILEX_FORCE_HTTPS is NOT set)
SSL: looking for env vars SILEX_SSL_CERTIFICATE and SILEX_SSL_PRIVATE_KEY
Listening on 6805

```

**Comment by tariqbenezza** [comment]
First tests on macOS High Sierra
Version 10.13.5

1- Is it Silex logo ?

<img width="329" alt="screen shot 2018-09-04 at 13 34 15" src="https://user-images.githubusercontent.com/4911564/45028977-5630b780-b047-11e8-8a88-c36ba38d896a.png">

2- The install ran successfully but now impossible to open it

<img width="1126" alt="screen shot 2018-09-04 at 13 38 35" src="https://user-images.githubusercontent.com/4911564/45029127-f2f35500-b047-11e8-92f6-655290c24bf0.png">

Got only the horizontal menu with silex and when I click on it it proposes only to "quit"

<img width="483" alt="screen shot 2018-09-04 at 13 39 59" src="https://user-images.githubusercontent.com/4911564/45029174-1e763f80-b048-11e8-8893-a217c54347bb.png">

Maybe I did something wrong ?

**Comment by lexoyo** [comment]
Hmm ...
You don't have Silex in your apps?

**Comment by JbIPS** [comment]
That's the lite version, please give Apple 20 dollars to get the full app :stuck_out_tongue_winking_eye:

**Comment by tariqbenezza** [comment]
Got a Silex app but nothing in the menu as you can see in my screenshot, and most important it seems that the app is not running properly

**Comment by BaguetteAgile** [comment]
Je test `Test silex-2.2.7-amd64.deb on linux`, voici les messages d'erreurs de la console

> jp@jp-desktop:~$ silex
Gtk-Message: 09:13:33.380: Failed to load module "canberra-gtk-module"
Silex starts with version [ '2', '2', '7' ]
FTP service: looking for env vars ENABLE_FTP
SFTP service: looking for env vars ENABLE_SFTP
Webdav service: looking for env vars ENABLE_WEBDAV
Github service: looking for env vars GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET
Dropbox service: looking for env vars DROPBOX_CLIENT_ID and DROPBOX_CLIENT_SECRET
Local file system service: looking for env vars SILEX_ELECTRON or SILEX_DEBUG or ENABLE_FS
body-parser deprecated undefined extended: provide extended option ../../opt/silex/resources/app.asar/node_modules/cloud-explorer/lib/router.js:297:53
force SSL NOT active (env var SILEX_FORCE_HTTPS is NOT set)
SSL: looking for env vars SILEX_SSL_CERTIFICATE and SILEX_SSL_PRIVATE_KEY
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE :::6805
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at Function.listen (/opt/silex/resources/app.asar/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/opt/silex/resources/app.asar/dist/server/index.js:67:5)
    at Object.<anonymous> (/opt/silex/resources/app.asar/dist/server/index.js:73:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/silex/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/silex/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)

**Comment by lexoyo** [comment]
Baguette and @gustavklopp it looks like you have another Silex running on your local computer? It says the port is busy :-/

Tariq, let's debug on Linux first then...

**Comment by gustavklopp** [comment]
Okay, thanks. 
Here's the error when I try to save a webpage:
Error: I did not manage to save the file.

```
Error: Unknown connector: undefined
    at Unifile.callMethod (/opt/silex/resources/app.asar/node_modules/unifile/lib/index.js:333:41)
    at Unifile.writeFile (/opt/silex/resources/app.asar/node_modules/unifile/lib/index.js:239:15)
    at writeWebsite (/opt/silex/resources/app.asar/dist/server/WebsiteRouter.js:118:13)
    at Layer.handle [as handle_request] (/opt/silex/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/silex/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/silex/resources/app.asar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/silex/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at /opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:281:22
    at param (/opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:354:14)
    at param (/opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:365:14)
    at param (/opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:410:3)
    at next (/opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:174:3)
    at router (/opt/silex/resources/app.asar/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/opt/silex/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
```

And here is the error when I try to import any `html` file:
```
Error: Unknown connector: undefined
    at Unifile.callMethod (/opt/silex/resources/app.asar/node_modules/unifile/lib/index.js:333:41)
    at Unifile.writeFile (/opt/silex/resources/app.asar/node_modules/unifile/lib/index.js:239:15)
    at Router.post (/opt/silex/resources/app.asar/node_modules/cloud-explorer/lib/router.js:248:38)
    at Layer.handle [as handle_request] (/opt/silex/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/silex/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Array.<anonymous> (/opt/silex/resources/app.asar/node_modules/multer/lib/make-middleware.js:53:37)
    at listener (/opt/silex/resources/app.asar/node_modules/on-finished/index.js:169:15)
    at onFinish (/opt/silex/resources/app.asar/node_modules/on-finished/index.js:100:5)
    at callback (/opt/silex/resources/app.asar/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/opt/silex/resources/app.asar/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```
I'm on Manjaro (Arch Linux based)

**Comment by BaguetteAgile** [comment]
En effet @lexoyo , après arrêt des processus 'Silex' et redémarrage du logiciel, voici le résultat de la console:

> jp@jp-desktop:~$ silex
Gtk-Message: 11:44:49.745: Failed to load module "canberra-gtk-module"
Silex starts with version [ '2', '2', '7' ]
FTP service: looking for env vars ENABLE_FTP
SFTP service: looking for env vars ENABLE_SFTP
Webdav service: looking for env vars ENABLE_WEBDAV
Github service: looking for env vars GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET
Dropbox service: looking for env vars DROPBOX_CLIENT_ID and DROPBOX_CLIENT_SECRET
Local file system service: looking for env vars SILEX_ELECTRON or SILEX_DEBUG or ENABLE_FS
body-parser deprecated undefined extended: provide extended option ../../opt/silex/resources/app.asar/node_modules/cloud-explorer/lib/router.js:297:53
force SSL NOT active (env var SILEX_FORCE_HTTPS is NOT set)
SSL: looking for env vars SILEX_SSL_CERTIFICATE and SILEX_SSL_PRIVATE_KEY
Listening on 6805

le logiciel ne se lance pas...

**Comment by gustavklopp** [comment]
@BaguetteAgile  It's not launching...  you must open `localhost:6805` in your browser!

**Comment by lexoyo** [comment]
It looks like it starts with `npm start` and no env vars @JbIPS

**Comment by lexoyo** [comment]
Hello 
The release of a desktop / offline version for linux and macos is now automatic, thx @JbIPS 
Please test the beta version here
https://github.com/silexlabs/Silex/releases/tag/v2.3.0

**Comment by netalex** [comment]
just test installed last version, 2.4.0, and it starts up does'nt open any window on my mac. macBookPro w. SIERRA 10.12.6 (i know, outdated os)

**Comment by msalini** [comment]
Just installed the deb package of version 2.4.0 on Linux Mint 18.3 (based on Ubuntu xenial) and likewise, the process starts with this message:

`
Silex starts with backward compat version [ 2, 2, 8 ] and front end version [ 2, 8 ]
/opt/silex/resources/app.asar/node_modules
 `

and it gets stuck:  the window won't open.

**Comment by lexoyo** [comment]
Hello
Silex desktop version seems buggy :(
Maybe you should use npm version?
https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#as-a-web-app-silex-web-version

**Comment by yumyo** [comment]
> First tests on macOS High Sierra
> Version 10.13.5
> 
> 1- Is it Silex logo ?
> 
> <img alt="screen shot 2018-09-04 at 13 34 15" width="329" src="https://user-images.githubusercontent.com/4911564/45028977-5630b780-b047-11e8-8a88-c36ba38d896a.png">
> 
> 2- The install ran successfully but now impossible to open it
> 
> <img alt="screen shot 2018-09-04 at 13 38 35" width="1126" src="https://user-images.githubusercontent.com/4911564/45029127-f2f35500-b047-11e8-92f6-655290c24bf0.png">
> 
> Got only the horizontal menu with silex and when I click on it it proposes only to "quit"
> 
> <img alt="screen shot 2018-09-04 at 13 39 59" width="483" src="https://user-images.githubusercontent.com/4911564/45029174-1e763f80-b048-11e8-8893-a217c54347bb.png">
> 
> Maybe I did something wrong ?

Same here

**Comment by lexoyo** [comment]
I believe you did not do anything wrong 
Maybe it just doesn't work properly
I published a new release with the latest silex version, can you try with this one please?
https://github.com/silexlabs/Silex/releases/tag/v2.5.43

**Comment by lexoyo** [comment]
Bump @jbips

**Comment by lexoyo** [comment]
Bump @JbIPS + maybe this is interesting for us more than appimage?
https://flathub.org/home

**Comment by mgiammarco** [comment]
I am trying desktop version too and it does not open windows. Tried also with localhost:6805 without luck. I have tried version 2.4.0 and version 2.5.43.

**Comment by HanzHaxors** [comment]
Waiting for Windows version 🥳 ⌛

**Comment by lexoyo** [comment]
Hi @HanzHaxors 
There is one since yesterday! :)
https://github.com/silexlabs/silex-desktop/releases
Let me know what you think about it

**Comment by HanzHaxors** [comment]
Nice work! I appreciate it :)
